#!/usr/bin/env sh

# A drush wrapper for local project environment.
# Contents of this file has been generated by bootstrap script.

# Configuration
DRUSH_CMD="%(drush_cmd)s"
WWW_DIR="%(www_dir)s"
COMMAND_DIRS="%(command_dirs)s"
DRUSH_PHP="%(php)s"

# Drush wrapper
export DRUSH_PHP
$DRUSH_CMD --include=$COMMAND_DIRS --root=$WWW_DIR $@
